# Generated by Django 4.2.2 on 2023-06-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="username",
            field=models.CharField(max_length=150),
        ),
    ]
