# Generated by Django 4.2.2 on 2023-06-27 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_myuser_username"),
    ]

    operations = [
        migrations.AlterModelOptions(name="myuser", options={},),
        migrations.AlterModelTable(name="myuser", table="gmsUsers",),
    ]
