# Generated by Django 4.2.2 on 2023-07-04 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_myuser_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyHeadAddresses",
            fields=[
                (
                    "family_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("house_number", models.CharField(max_length=10, unique=True)),
                ("floor_number", models.IntegerField(max_length=2, unique=True)),
                ("address", models.CharField(max_length=50, unique=True)),
            ],
            options={"db_table": "family_head_address",},
        ),
        migrations.CreateModel(
            name="FamilyHeadtoMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "family_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_head",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family_members",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "head_to_member_relation",},
        ),
    ]
