# Generated by Django 4.2.2 on 2023-07-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_myuser_aadhar_number_alter_myuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="username",
            field=models.CharField(default=None, null=True),
        ),
    ]
