# Generated by Django 4.2.2 on 2023-07-04 11:42

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_myuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="aadhar_number",
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
