# Generated by Django 4.2.2 on 2023-07-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_myuser_aadhar_number_alter_myuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familyheadaddresses",
            name="floor_number",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="aadhar_number",
            field=models.CharField(max_length=12),
        ),
    ]
