# Generated by Django 4.2.2 on 2023-07-04 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_familyheadaddresses_floor_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familyheadaddresses",
            name="floor_number",
            field=models.IntegerField(
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="username",
            field=models.CharField(max_length=150),
        ),
    ]
