# Generated by Django 4.2.2 on 2023-07-04 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_familyheadaddresses_floor_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familyheadaddresses",
            name="family_head",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                to_field="phone_number",
            ),
        ),
        migrations.AlterField(
            model_name="familyheadtomember",
            name="family_head",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="family_head",
                to=settings.AUTH_USER_MODEL,
                to_field="phone_number",
            ),
        ),
        migrations.AlterField(
            model_name="familyheadtomember",
            name="family_members",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="family_member",
                to=settings.AUTH_USER_MODEL,
                to_field="phone_number",
            ),
        ),
    ]
